/* Generated By:JavaCC: Do not edit this line. ROSMOPParserConstants.java */
package rosmop.parser.main_parser;


/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ROSMOPParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int WHITESPACE = 1;
  /** RegularExpression Id. */
  int LINECOMMENT = 2;
  /** RegularExpression Id. */
  int BLOCKCOMMENT = 3;
  /** RegularExpression Id. */
  int LBRACE = 4;
  /** RegularExpression Id. */
  int RBRACE = 5;
  /** RegularExpression Id. */
  int LPAREN = 6;
  /** RegularExpression Id. */
  int RPAREN = 7;
  /** RegularExpression Id. */
  int COLON = 8;
  /** RegularExpression Id. */
  int AT = 9;
  /** RegularExpression Id. */
  int EVENT = 10;
  /** RegularExpression Id. */
  int INIT = 11;
  /** RegularExpression Id. */
  int ID = 12;
  /** RegularExpression Id. */
  int DIGIT = 13;
  /** RegularExpression Id. */
  int LETTER = 14;
  /** RegularExpression Id. */
  int BACKTICK = 15;
  /** RegularExpression Id. */
  int COMMA = 16;
  /** RegularExpression Id. */
  int NAMING = 17;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "<WHITESPACE>",
    "<LINECOMMENT>",
    "<BLOCKCOMMENT>",
    "\"{\"",
    "\"}\"",
    "\"(\"",
    "\")\"",
    "\":\"",
    "\"@\"",
    "\"event\"",
    "\"init\"",
    "<ID>",
    "<DIGIT>",
    "<LETTER>",
    "\"`\"",
    "\",\"",
    "<NAMING>",
    "\"\\\'\"",
  };

}
